config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :news
  resources :categories
  get '/all_news',  to: 'news#all_news', as: "all_news"
  root "news#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :categories

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :admin_user, class_name: 'AdminUser', foreign_key: 'author_id'
    belongs_to :category

    mount_uploader :image, ImageUploader

    validates :title, presence: true, length: { minimum: 3 }

    enum status: { not_published: 0, published: 1 }

    def self.ransackable_attributes(auth_object = nil)
        ["author_id", "author_name", "category_id", "content", "created_at", "id", "image", "status", "title", "updated_at"]
      end

      def self.ransackable_associations(auth_object = nil)
        ["admin_user", "category"]
      end
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :articles
    belongs_to :admin_user , class_name: 'AdminUser', foreign_key: 'author_id'

    def self.ransackable_attributes(auth_object = nil)
        ["author_id", "created_at", "description", "id", "name", "updated_at"]
      end

      def self.ransackable_associations(auth_object = nil)
        ["articles"]
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find_by(id: params[:id])
    @news = Article.where(category_id: @category.id) if @category.present?
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def index
    @news = Article.limit(3)
    @categories = Category.where("categories.name is not null")
    @api_news = ApiNews.new("Api News").fetch_news
    @image = "https://assets-prd.punchdrink.com/wp-content/uploads/2019/10/23100724/Article-Fifty-Fifty-50-50-Martini-Really-a-Martini-Cocktail.jpg"
  end

  def all_news
    @news = params[:search].present? ? Article.joins(:category).where("categories.name ilike ? or articles.title ilike ?","%#{params[:search]}%","%#{params[:search]}%") : Article.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/categories/show.html.erb
<br>
<br>
<h1 class="text-center"><%= @category.name %> News</h1>
<div class="container">
  <div class ="row">
    <% @news.each_with_index do |news, index| %>
      <div class="card col-lg-4 col-md-6 col-sm-12 article">

        <span
          data-url="<%= news.title %>"
          class="article-title"
          id="article-<%= index %>"
          title="<%= news.title%>"
          style="font-weight: bold;"
        >
            <%= news.title %>
        </span>

        <span><%= news.title %></span>
        <%= image_tag(news.image.url || @image_placeholder, class: 'card-img-top') %>
        <div class="card-body">
          <h5 class="card-title"><% news.title %></h5>
          <p class="card-text"> <%= news.content %></p>
        </div>
        <%# if current_user %>
        <!--          <i data-article-key="<%#= article_key %>"  class="far fa-bookmark bookmark" data-toggle="modal" data-target="#create-bookmark"></i>-->
        <%# end %>
      </div>
    <% end %>
  </div>
</div>

<%# if current_user %>
<%#= render 'bookmark' %>
<%# end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
  <div class="container-fluid">
    <%= link_to "News", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% @categories&.each do |cat| %>
              <%= link_to cat.name.capitalize, category_path(cat), class: "dropdown-item" %>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul>

      </ul>
        <l1 class="nav-item">
          <%= form_tag all_news_path, :method => "get", :class => "d-flex" do %>
            <%=  text_field_tag :search, params[:search], class: "form-control mr-sm-2 nav-link", placeholder: "Search News" %>
            <%= submit_tag("Search", :name=>nil) %>
          <% end %>
        </l1>

      <li><%= link_to 'Login as Admin', new_admin_user_session_path %></li>
        <%#= render 'layouts/auth' %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/news/_news.html.erb
<div class="container">
  <div class ="row">
    <% @news.each_with_index do |news, index| %>
      <div class="card col-lg-4 col-md-6 col-sm-12 article">

        <span
          data-url="<%= news.title %>"
          class="article-title"
          id="article-<%= index %>"
          title="<%= news.title%>"
          style="font-weight: bold;"
        >
            <%= news.title %>
        </span>

        <span><%= news.title %></span>
        <%= image_tag(news.image.url || @image_placeholder, class: 'card-img-top') %>
        <div class="card-body">
          <h5 class="card-title"><% news.title %></h5>
          <p class="card-text"> <%= news.content %></p>
        </div>
        <%# if current_user %>
<!--          <i data-article-key="<%#= article_key %>"  class="far fa-bookmark bookmark" data-toggle="modal" data-target="#create-bookmark"></i>-->
        <%# end %>
      </div>
    <% end %>
  </div>
</div>

<%# if current_user %>
  <%#= render 'bookmark' %>
<%# end %>

app/views/news/all_news.html.erb
<br>
<br>
<h1 class="text-center">All News</h1>
<%= render 'news' %>

app/views/news/index.html.erb
<br>
<br>
<h1 class="text-center">Top News</h1>
<%= render 'news' %>
<br>
<h4 class="text-center"><%= link_to "All News", all_news_path %></h4>
<h1 class="text-center">Api News</h1>
<div class="container">
  <div class ="row">
    <% @api_news&.each_with_index do |response, news_key| %>
      <div class="card col-lg-4 col-md-6 col-sm-12 article">

        <span
          data-url="<%= response['url'] %>"
          class="article-title"
          id="article-<%= news_key %>"
          title="<%= response['title']%>"
          style="font-weight: bold;"
        >
            <%= response['title'] %>
        </span>

        <span><%= response['source']['name'] %></span>
        <%= image_tag(response['urlToImage'] || @image, class: 'card-img-top') %>
        <div class="card-body">
          <h5 class="card-title"><% response['title'] %></h5>
          <p class="card-text"> <%= response['description'] %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>